const args = process.argv.slice(2);
const fs = require('fs');
const WebSocket = require('ws');
// Generated by Nyapilot
// Initialisation d'un client WebSocket

//récupération de la liste des fichiers dans le dossier
const files = fs.readdirSync('./');
if (!files.includes(args[0])||args.length === 0) {
    console.error('Le fichier spécifié n\'existe pas');
    console.error('Liste des fichiers disponibles:');
    files.forEach(file => {
        console.log(file);
    });
    process.exit(1);
}
const userID = args[1] || 507816376795267072;


const ws = new WebSocket('ws://localhost:8080', {
    perMessageDeflate: false
});

ws.on('open', function open() {
    console.log('Connecté au serveur WebSocket');
    ws.requestID = {};// {requestID: callback}
    ws.onse = (requestID, callback) => {
        ws.requestID[requestID] = callback;
    }
    ws.init = () => {//initialisation de l'écoute des messages
        ws.on('message', (data) => {
            const message = JSON.parse(data);
            if (ws.requestID[message.requestID]) {
                ws.requestID[message.requestID](message);
                delete ws.requestID[message.requestID];
            }
        }); 
    }
    ws.sendAndAwait = (message, callback) => {
        ws.send(JSON.stringify(message));
        ws.onse(message.requestID, callback);
    }
    require(`./${args[0]}`)(ws, userID);
});


ws.on('close', function close() {
    console.log('Déconnecté du serveur WebSocket');
});

ws.on('error', function error(err) {
    console.error(`Erreur: ${err.message}`);
});