const snowflake = require('../lib/snowflake');
function bigIntToStringInBase(num, base) {
    if (base <= 36) {
        return num.toString(base); // Utilise la fonction toString si la base est ≤ 36
    }

    let result = '';
    let current = BigInt(num);

    // Boucle pour récupérer les valeurs et les convertir
    while (current > 0) {
        let remainder = Number(current % BigInt(base));
        current /= BigInt(base);

        // Pour les valeurs supérieures à 9, utiliser des lettres
        if (remainder < 10) {
            result = remainder + result;
        } else {
            result = String.fromCharCode(87 + remainder) + result; // 87 convertit 10 -> 'a', 11 -> 'b', etc.
        }
    }

    return result || '0';
}

// Generated by Nyapilot
// Fonction pour convertir une chaîne en nombre dans une base donnée
function stringInBaseToBigInt(str, base, baseOut = 10) {
    let result = BigInt(0);
    let multiplier = BigInt(1);

    // Boucle pour convertir chaque caractère
    for (let i = str.length - 1; i >= 0; i--) {
        let value;
        let char = str[i];

        // Détermine la valeur du caractère
        if (char >= '0' && char <= '9') {
            value = BigInt(char.charCodeAt(0) - '0'.charCodeAt(0));
        } else {
            value = BigInt(char.charCodeAt(0) - 87); // 87 convertit 'a' -> 10, 'b' -> 11, etc.
        }

        result += value * multiplier;
        multiplier *= BigInt(base);
    }

    return result;
}
module.exports = function (ws,userID) {

    //crée des snowflakes
    for (let i = 0; i < 10; i++) {
        console.log(snowflake('user').raw);
    }

    //convertit des nombres en base 36 et 64
    console.log("("+bigIntToStringInBase(123456789, 2)+")_2");
    console.log("("+bigIntToStringInBase(123456789, 8)+")_8");
    console.log("("+bigIntToStringInBase(123456789, 10)+")_10");
    console.log("("+bigIntToStringInBase(123456789, 16)+")_16");
    console.log("("+bigIntToStringInBase(123456789, 36)+")_36");
    console.log("("+bigIntToStringInBase(123456789, 64)+")_64");
    console.log("("+bigIntToStringInBase(123456789, 100000)+")_100000");
    console.log(stringInBaseToBigInt(bigIntToStringInBase(123456789, 100000),100000),stringInBaseToBigInt(bigIntToStringInBase(123456789, 100000),100000) == 123456789);

    // Generated by Nyapilot
    // Remplace chaque espace par un underscore
    const str = `salut tout le monde ce texte est converti en base 10`.replace(/ /g, "_");
    console.log(str);//moi_je_suis_un_snowflake
    console.log(stringInBaseToBigInt(str, 36));//14145382983038322470631956198011787198n
    console.log(bigIntToStringInBase(stringInBaseToBigInt(str, 36), 36));//moi8je8suis8un8snowflake
    ws.close();
}